DRILL-7812: updated hashCode function for MaterializedField
apache/drill pull request #2117
Opened 2020-11-26 11:52 UTC by rymarm

# [DRILL-7801](https://issues.apache.org/jira/browse/DRILL-7812): Broken equals/hashcode contract 

## Description
MaterializedField had broken hashCode/equals contract:

> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.

In our case, equals are based on 2 parameters, while hashCode on 3. I updated hashCode and now it respond equals function.
`this.name.toLowerCase()` was added, because equals method compares name with ignoreCase.

## Testing
Manual tests

2020-11-27 14:35 UTC, ihuzenko requested changes
Please add a unit test.

2020-11-27 14:35 UTC, ihuzenko commented on exec/vector/src/main/java/org/apache/drill/exec/record/MaterializedField.java
> +    return Objects.hash(this.name.toLowerCase(), this.type);
is it guaranteed that name is never null?

2021-01-05 16:19 UTC, cgivre commented
@ihuzenko 
Could you please take another look and see if this is ready to be merged?
Thanks!

2021-01-14 17:00 UTC, vdiravka approved these changes
@rymarm Good catch. +1
Let's give @ihuzenko a few days to take a look before merge.

2021-01-29 20:28 UTC, ihuzenko approved these changes
Looks Great !!! Thanks  @rymarm for making the changes and sorry for my delay.

2021-02-03 05:12 UTC, merged