DRILL-7712: Fix issues after ZK upgrade
apache/drill pull request #2168
Opened 2021-02-12 16:49 UTC by eevanwong

# [DRILL-7712](https://issues.apache.org/jira/browse/DRILL-7712): Fix Issues after ZK upgrade (Updated to resolve CI)

## Description

Updated unit test so that it utilizes MappingListenerManager instead of ListenerContainer from Apache Curator which was deprecated in version 5.1.0. Curator v5.1.0 fixes NPE errors in testing phase (also described in DRILL-7843(https://issues.apache.org/jira/browse/DRILL-7843).

## Documentation
N/A

## Testing
Checked mvn test and the errors that were described are no longer there. 

`[INFO] Running org.apache.drill.exec.coord.zk.TestZookeeperClient
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.224 s - in org.apache.drill.exec.coord.zk.TestZookeeperClient

[INFO] Running org.apache.drill.exec.coord.zk.TestEphemeralStore
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.658 s - in org.apache.drill.exec.coord.zk.TestEphemeralStore

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.555 s - in org.apache.drill.yarn.zk.TestAmRegistration

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.063 s - in org.apache.drill.yarn.client.TestCommandLineOptions`

Erros in jdbc-all build I believe are resolved from DRILL-7841 pr.

2021-02-13 02:00 UTC, luocooong commented
@eevanwong Thanks for your contribution. I saw that you closed the #2156 , then created this PR. If you plan to rebase your branch from master in the future, you can do that:
```
  1. git checkout <your_branch>
  2. git fetch upstream master
  3. git rebase upstream/master
  4. git push origin <your_branch> -f
```
There is no need to close the PR (could interrupt the previous review process). Once your PR was approved, you can combine multiple commits into one by git squash command. Enjoy!

2021-02-16 17:46 UTC, eevanwong commented
Bit of an update regarding the apache curator changes. 

I haven't been able to find any other of the breaking changes affecting drill; however, PathChildrenCache is deprecated in ZookeeperClient.java from org.apache.curator.framework.recipes.cache, and can be replaced with CuratorCache (although the methods and constructors are different), but I didn't encounter any issues while running drill in embedded mode (maybe it can be its own issue?).

2021-02-17 00:49 UTC, luocooong commented
@eevanwong About the tests of maprdb is here [drill-mapr-plugin](https://github.com/apache/drill/blob/master/contrib/format-maprdb/README.md)

2021-02-19 07:27 UTC, eevanwong commented
@vvysotskyi you had mentioned you had to use some tricks for maprDB to work on drill. I've encountered an error when I attempted to test it with mapR profile.  

```
[ERROR] com.mapr.drill.maprdb.tests.MaprDBTestsSuite  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/client/TableDescriptor
	at com.mapr.drill.maprdb.tests.MaprDBTestsSuite.setupTests(MaprDBTestsSuite.java:66 (edited
```

Also, I just want to confirm that testing with the proper profiles (as I am using the maven interface on intellij) 

![Screenshot (65)](https://user-images.githubusercontent.com/71536798/108471862-01ef1180-725a-11eb-844f-e7f02ea0daf9.png)

2021-02-19 07:43 UTC, vvysotskyi commented
@eevanwong, Drill wouldn't start these tests without mapr env, for now no need to run them.
I meant just to run 
```
mvn clean install -Pmapr
```

2021-02-24 17:56 UTC, eevanwong commented
> 
> 
> @eevanwong, Drill wouldn't start these tests without mapr env, for now no need to run them.
> I meant just to run
> 
> ```
> mvn clean install -Pmapr
> ```

When I try that, for some reason I get NPE errors with iceberg metastore tests.

```
[ERROR] Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 0.97 s <<< FAILURE! - in org.apache.drill.metastore.iceberg.components.tables.TestIcebergTablesMetastoreConfigAndVersion
[ERROR] org.apache.drill.metastore.iceberg.components.tables.TestIcebergTablesMetastoreConfigAndVersion.testLoadWithoutProperties  Time elapsed: 0.103 s  <<< ERROR!
java.lang.NullPointerException
        at org.apache.drill.metastore.iceberg.components.tables.TestIcebergTablesMetastoreConfigAndVersion.testLoadWithoutProperties(TestIcebergTablesMetastoreConfigAndVersion.java:107)
```

I don't get these errors w/o mapR profile.

2021-03-05 17:09 UTC, eevanwong commented
@vvysotskyi  I've encountered a few issues with the testing. With mapR prof enabled I tried testing in drill-format-mapR. 
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.053 s <<< FAILURE! - in com.mapr.drill.maprdb.tests.MaprDBTestsSuite
[ERROR] com.mapr.drill.maprdb.tests.MaprDBTestsSuite  Time elapsed: 0.01 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/client/TableDescriptor
	at com.mapr.drill.maprdb.tests.MaprDBTestsSuite.setupTests(MaprDBTestsSuite.java:66)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.client.TableDescriptor
	at com.mapr.drill.maprdb.tests.MaprDBTestsSuite.setupTests(MaprDBTestsSuite.java:66)
```
@luocooong seems to get the same error, and I'm starting to think that this would still be here even if the curator version was not updated. I'll test it just to make sure.

2021-03-06 16:26 UTC, luocooong commented
@eevanwong @vvysotskyi @cgivre All right. I think it means that there are errors before this upgrade : there may be no test condition for module of maprdb now. then run the mvn build with `mvn install -Dtests=cluster -Pmapr`, actually using the profile in following :
```xml
  <profiles>
    <profile>
      <id>mapr</id>
      <properties>
        <mapr.skip.tests>false</mapr.skip.tests>
      </properties>
    </profile>
    ...
```
Is it possible to review the PR without maprdb (test)? Please create new JIRA about the following issues :
```
java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/protobuf/generated/MasterProtos$MasterService$BlockingInterface
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:294)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:237)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:138)
	at org.apache.drill.hbase.HBaseTestsSuite.initCluster(HBaseTestsSuite.java:120)
```
and
```
java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/client/TableDescriptor
	at com.mapr.drill.maprdb.tests.MaprDBTestsSuite.setupTests(MaprDBTestsSuite.java:66)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.client.TableDescriptor
	at com.mapr.drill.maprdb.tests.MaprDBTestsSuite.setupTests(MaprDBTestsSuite.java:66)
```
So, We can't stop because of maprdb module, and speed up the review and merge is friendly for new contributor. thanks

2021-03-06 16:38 UTC, vvysotskyi approved these changes
Ok, if these errors aren't related to this change, it is not a blocker.
Thanks for updating Curator, +1

2021-03-06 16:58 UTC, luocooong requested changes
@vvysotskyi Thanks for the review.
@eevanwong Hi, Could you please following the steps below?
1. Create the JIRA about the above issues.
2. Manual testing in distributed mode for better (ensure the stability of real world).

Once all done, It's ready to merge. thanks

2021-03-07 03:00 UTC, eevanwong commented
> 
> 
> @vvysotskyi Thanks for the review.
> @eevanwong Hi, Could you please following the steps below?
> 
>     1. Create the JIRA about the above issues.
> 
>     2. Manual testing in distributed mode for better (ensure the stability of real world).
> 
> 
> Once all done, It's ready to merge. thanks

Ok, will do, being a bit busy this weekend I'll do it next monday.

2021-03-08 17:59 UTC, eevanwong commented
Hey I've made the [jira ticket](https://issues.apache.org/jira/projects/DRILL/issues/DRILL-7876?filter=addedrecently)

I also tried a variety of different queries, albeit not very complex ones.

`select education_level,max(salary) as maxSalary
2.......semicolon> from `employee.json`
3.......semicolon> group by education_level;
+---------------------+-----------+
|   education_level   | maxSalary |
+---------------------+-----------+
| Graduate Degree     | 80000.0   |
| Bachelors Degree    | 45000.0   |
| Partial College     | 50000.0   |
| High School Degree  | 17000.0   |
| Partial High School | 13000.0   |
+---------------------+-----------+`

`
apache drill (cp)> select employee_id,full_name,salary from `employee.json` where store_id = 9 and education_level = 'Bachelors Degree';
+-------------+----------------+---------+
| employee_id |   full_name    | salary  |
+-------------+----------------+---------+
| 8           | Kim Brunner    | 10000.0 |
| 733         | Wanda Vernon   | 5900.0  |
| 742         | Mae Anderson   | 3700.0  |
| 744         | Chris Bidelman | 20.0    |
| 746         | Sara Breer     | 20.0    |
+-------------+----------------+---------+
`

2021-03-09 05:11 UTC, luocooong approved these changes
@eevanwong +1
Thanks a lot. And looking forward to your next contribution.

2021-03-10 12:30 UTC, merged