[DRAFT] Fix DateFormat in DateGen.java
apache/drill pull request #2959
Opened 2024-10-26 23:04 UTC by pjfanning

See #2958 

This change is experimental.

2024-10-26 23:06 UTC, pjfanning commented on exec/java-exec/src/main/java/org/apache/drill/exec/store/mock/DateGen.java
> +    final long randTime = baseTime + baseTime + rand.nextInt(365) * ONE_DAY;
@jnturton @cgivre this doesn't look right - baseTime is a big number but we add it twice so the result will be a very big number, a long way in the future.

2025-03-12 18:06 UTC, cgivre requested changes

2025-03-12 18:06 UTC, cgivre commented on exec/java-exec/src/main/java/org/apache/drill/exec/store/mock/DateGen.java
> +    final long randTime = baseTime + baseTime + rand.nextInt(365) * ONE_DAY;
@pjfanning What if you just make it: 
```
long randTime = baseTime + (rand.nextInt(365)* ONE_DAY)
```

2025-03-13 13:45 UTC, pjfanning commented
@cgivre I made the change to the randTime calculation

2025-03-13 14:11 UTC, cgivre approved these changes
LGTM +1

2025-03-13 14:12 UTC, merged